export const appConstants = {
    SWITCH_LANGUAGE_ES: 'SWITCH_LANGUAGE_ES',
    SWITCH_LANGUAGE_EN: 'SWITCH_LANGUAGE_EN',
    SET_LOADING: 'SET_LOADING'
}

export const mapConstants = {
    HANDLE_MAP_READY: 'HANDLE_MAP_READY',
    SET_MAP_TYPE: 'SET_MAP_TYPE',
    SET_AUTO_CENTER_DEVICE: 'SET_AUTO_CENTER_DEVICE',
    SET_SHOWING_MAP_TYPES: 'SET_SHOWING_MAP_TYPES',
    SET_SHOWING_MARKER_TAIL: 'SET_SHOWING_MARKER_TAIL',
    SET_SHOWING_GEOFENCES: 'SET_SHOWING_GEOFENCES',
    SET_SHOWING_POIS: 'SET_SHOWING_POIS',
    SET_SHOWING_USER_LOCATION: 'SET_SHOWING_USER_LOCATION'
}
 
export const deviceConstants = {
    SET_DEVICES: 'SET_DEVICES',
    SET_DEVICES_SHOWN: 'SET_DEVICES_SHOWN',
    SET_DEVICES_MODELS: 'SET_DEVICES_MODELS',
    HANDLE_NEW_GPS_DATA: 'HANDLE_NEW_GPS_DATA',
    SHOW_DEVICE_ON_MAP: 'SHOW_DEVICE_ON_MAP',
    REMOVE_DEVICE_FROM_MAP: 'REMOVE_DEVICE_FROM_MAP',
    SET_HISTORY_TYPE: 'SET_HISTORY_TYPE',
    SET_HISTORY_DATA: 'SET_HISTORY_DATA',
    SET_HISTORY_COORDS_DATA: 'SET_HISTORY_COORDS_DATA',
    SET_HISTORY_HIGHER_SPEED: 'SET_HISTORY_HIGHER_SPEED',
    SET_HISTORY_DISTANCE: 'SET_HISTORY_DISTANCE',
    SET_HISTORY_TIME_MOVE: 'SET_HISTORY_TIME_MOVE',
    SET_HISTORY_TIME_STOP: 'SET_HISTORY_TIME_STOP',
    SET_HISTORY_ALERTS_TIME: 'SET_HISTORY_ALERTS_TIME',
    SET_HISTORY_FUEL_CONSUMPTION: 'SET_HISTORY_FUEL_CONSUMPTION'
}

export const userConstants = {
    SET_USER: 'SET_USER'
}

export const groupConstants = {
    SET_GROUPS: 'SET_GROUPS'
}