export const appConstants = {
    SWITCH_LANGUAGE_ES: 'SWITCH_LANGUAGE_ES',
    SWITCH_LANGUAGE_EN: 'SWITCH_LANGUAGE_EN',
    SET_LOADING: 'SET_LOADING',
    SET_SOCKET: 'SET_SOCKET'
}

export const mapConstants = {
    HANDLE_MAP_READY: 'HANDLE_MAP_READY',    
    SET_DEVICE_LOCATIONS: 'SET_DEVICE_LOCATIONS'
}
 
export const deviceConstants = {
    SET_DEVICES: 'SET_DEVICES',
    SET_DEVICES_SHOWN: 'SET_DEVICES_SHOWN',
    SET_DEVICES_MODELS: 'SET_DEVICES_MODELS',
    HANDLE_NEW_GPS_DATA: 'HANDLE_NEW_GPS_DATA',
    SHOW_DEVICE_ON_MAP: 'SHOW_DEVICE_ON_MAP',
    REMOVE_DEVICE_FROM_MAP: 'REMOVE_DEVICE_FROM_MAP',
    SET_HISTORY_TYPE: 'SET_HISTORY_TYPE',
    SET_HISTORY_DATA: 'SET_HISTORY_DATA',
    SET_HISTORY_COORDS_DATA: 'SET_HISTORY_COORDS_DATA',
    SET_HISTORY_HIGHER_SPEED: 'SET_HISTORY_HIGHER_SPEED',
    SET_HISTORY_DISTANCE: 'SET_HISTORY_DISTANCE',
    SET_HISTORY_TIME_MOVE: 'SET_HISTORY_TIME_MOVE',
    SET_HISTORY_TIME_STOP: 'SET_HISTORY_TIME_STOP',
    SET_HISTORY_ALERTS_TIME: 'SET_HISTORY_ALERTS_TIME',
    SET_HISTORY_FUEL_CONSUMPTION: 'SET_HISTORY_FUEL_CONSUMPTION',
    SET_IS_SELECTED_IN_GROUPS: 'SET_IS_SELECTED_IN_GROUPS',
    SET_DEVICES_LOCATIONS: 'SET_DEVICES_LOCATIONS'
}

export const userConstants = {
    SET_USER: 'SET_USER'
}

export const groupConstants = {
    SET_GROUPS: 'SET_GROUPS'
}

export const geofenceConstants = {
    SET_GEOFENCES: 'SET_GEOFENCES',
    SET_GEOFENCE_ID: 'SET_GEOFENCE_ID',
    SET_GEOFENCE_NAME: 'SET_GEOFENCE_NAME',
    SET_GEOFENCE_DESCRIPTION: 'SET_GEOFENCE_DESCRIPTION',
    SET_GEOFENCE_TYPE: 'SET_GEOFENCE_TYPE',
    SET_GEOFENCE_COLOR: 'SET_GEOFENCE_COLOR',
    SET_GEOFENCE_ENABLED: 'SET_GEOFENCE_ENABLED',
    SET_GEOFENCE_POINTS: 'SET_GEOFENCE_POINTS',
    SET_GEOFENCE_CENTER: 'SET_GEOFENCE_CENTER',
    SET_GEOFENCE_RADIUS: 'SET_GEOFENCE_RADIUS'    
}